server:
  port: 8083

spring:
  application:
    name: zuul-server

zuul:
  routes:
    servicio:
      path: /api/v2.0/**
      url: http://10.225.125.175:8091/
      strip-prefix: false

    proyecto:
      path: /api/v1.0/**
      url: http://10.225.125.175:8081/
      strip-prefix: false

eureka:
  instance:
    prefer-ip-address: true

  client:
    register-with-eureka: true
    
    fetch-registry: true
    
    service-url:
     defaultzone: http://10.225.125.175:8761/eureka/
     
management:
  endpoint:
    routes:
      enabled: true
      
  endpoints:
    web:
      exposure:
        include: "*"